# Generated by Django 5.0.3 on 2024-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_members_delete_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
